name: CI - Nextjs Build and Lint
on:
  push: 
    branches: [release/prod, main]
  pull_request:
    branches: [release/prod, main]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23.3.0

      - name: Install dependencies
        run: npm install

      - name: Lint check
        run: npm run lint
        
      - name: Build Next.js app
        run: npm run build